-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.categories (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  parent_id bigint,
  level integer DEFAULT 0,
  color text DEFAULT '#3B82F6'::text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  is_featured boolean DEFAULT false,
  product_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  kiotviet_id text UNIQUE,
  last_synced_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'synced'::text, 'failed'::text, 'syncing'::text])),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.clients (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  birthday date,
  location text,
  description text,
  order_count integer DEFAULT 0 CHECK (order_count >= 0),
  created_by bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  gender text CHECK (gender = ANY (ARRAY['Male'::text, 'Female'::text, 'Other'::text])),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.commission_rates (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_level text NOT NULL UNIQUE CHECK (user_level = ANY (ARRAY['guest'::text, 'member'::text, 'unit manager'::text, 'brand manager'::text])),
  self_commission numeric NOT NULL DEFAULT 0 CHECK (self_commission >= 0::numeric AND self_commission <= 100::numeric),
  level_1_down numeric NOT NULL DEFAULT 0 CHECK (level_1_down >= 0::numeric AND level_1_down <= 100::numeric),
  level_2_down numeric NOT NULL DEFAULT 0 CHECK (level_2_down >= 0::numeric AND level_2_down <= 100::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT commission_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  order_id bigint NOT NULL,
  product_id bigint NOT NULL,
  product_name text NOT NULL,
  product_sku text,
  product_price numeric NOT NULL CHECK (product_price >= 0::numeric),
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  line_total numeric NOT NULL CHECK (line_total >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.orders (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  order_number text NOT NULL UNIQUE,
  subtotal_amount numeric NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0::numeric),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'confirmed'::text, 'shipped'::text, 'delivered'::text, 'completed'::text, 'cancelled'::text, 'refunded'::text])),
  payment_method text CHECK (payment_method = ANY (ARRAY['cash'::text, 'card'::text, 'bank_transfer'::text, 'credit'::text, 'other'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'failed'::text, 'refunded'::text])),
  payment_date timestamp with time zone,
  client_id bigint,
  created_by bigint NOT NULL,
  notes text,
  shipping_address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.otps (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  phone text NOT NULL,
  code text NOT NULL,
  purpose text NOT NULL CHECK (purpose = ANY (ARRAY['signup'::text, 'password_reset'::text])),
  user_id bigint,
  expires_at timestamp with time zone NOT NULL,
  verified boolean DEFAULT false,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT otps_pkey PRIMARY KEY (id),
  CONSTRAINT otps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.product_categories (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  product_id bigint NOT NULL,
  category_id bigint NOT NULL,
  is_primary boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_categories_pkey PRIMARY KEY (id),
  CONSTRAINT product_categories_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.product_images (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  product_id bigint NOT NULL,
  storage_path text NOT NULL,
  url text NOT NULL,
  alt_text text,
  sort_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  file_size integer,
  width integer,
  height integer,
  mime_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  slug text UNIQUE,
  sku text UNIQUE,
  short_description text NOT NULL,
  long_description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  cost_price numeric CHECK (cost_price >= 0::numeric),
  stock integer CHECK (stock >= 0),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'inactive'::text, 'archived'::text])),
  is_featured boolean DEFAULT false,
  created_by bigint,
  updated_by bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  kiotviet_id text UNIQUE,
  serial_number text,
  supplier_id text,
  center_stone_size_mm numeric,
  shape text,
  dimensions text,
  stone_count integer,
  carat_weight_ct numeric,
  gold_purity text,
  product_weight_g numeric,
  inventory_value numeric,
  last_synced_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'synced'::text, 'failed'::text, 'syncing'::text])),
  ni_tay numeric,
  type text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT products_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.sync_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  integration_id bigint,
  sync_type text NOT NULL CHECK (sync_type = ANY (ARRAY['full'::text, 'incremental'::text, 'manual'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text, 'partial'::text])),
  products_synced integer DEFAULT 0,
  products_created integer DEFAULT 0,
  products_updated integer DEFAULT 0,
  products_failed integer DEFAULT 0,
  categories_synced integer DEFAULT 0,
  categories_created integer DEFAULT 0,
  categories_updated integer DEFAULT 0,
  categories_failed integer DEFAULT 0,
  error_message text,
  error_details jsonb,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT sync_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.third_party_integrations(id)
);
CREATE TABLE public.third_party_integrations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  display_name text NOT NULL,
  api_url text NOT NULL,
  token_url text,
  client_id text,
  client_secret text,
  retailer text,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  sync_enabled boolean DEFAULT true,
  last_sync_at timestamp with time zone,
  sync_interval_minutes integer DEFAULT 60,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT third_party_integrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_avatars (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id bigint NOT NULL UNIQUE,
  storage_path text NOT NULL,
  url text NOT NULL,
  file_size integer,
  width integer,
  height integer,
  mime_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  viewport_x numeric,
  viewport_y numeric,
  viewport_size numeric,
  CONSTRAINT user_avatars_pkey PRIMARY KEY (id),
  CONSTRAINT user_avatars_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_personal_ids (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id bigint NOT NULL UNIQUE,
  front_image_path text NOT NULL,
  front_image_url text NOT NULL,
  back_image_path text,
  back_image_url text,
  file_size integer,
  mime_type text,
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  verified_by bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_personal_ids_pkey PRIMARY KEY (id),
  CONSTRAINT user_personal_ids_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_personal_ids_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  email text UNIQUE,
  name text,
  password text,
  role text NOT NULL DEFAULT 'user'::text,
  points integer DEFAULT 0,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  level text DEFAULT 'guest'::text CHECK (level = ANY (ARRAY['guest'::text, 'member'::text, 'unit manager'::text, 'brand manager'::text])),
  refer_code text DEFAULT upper(SUBSTRING(md5((random())::text) FROM 1 FOR 6)) UNIQUE,
  commission integer NOT NULL DEFAULT 0,
  phone text,
  address text,
  referred_by text,
  phone_verified boolean DEFAULT false,
  location character varying,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);